version: '3.9'

services:
  wordapp:
    container_name: wordapp
    image: wordapp
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/worddb
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=worddb
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}